---
- name: "Commvault StoreFront Clean-up"
  hosts: commvault
  become: true
  vars:
    remote_script_path: /var/www/html/attackfiles/postclean.sh

  tasks:

    - name: Ensure the script is executable
      file:
        path: "{{ remote_script_path }}"
        mode: '0755'
        owner: root
        group: root

    - name: Execute the cleanup script
      shell: "{{ remote_script_path }}"
      register: cleanup_output

    - name: Show script output
      debug:
        var: cleanup_output.stdout_lines

    - name: Print cleanup results
      debug:
        msg: "{{ cleanup_output.stdout_lines }}"
