---
- name: Deploy SSH public key to new hosts
  hosts: all
  gather_facts: no

  vars_prompt:
    - name: ansible_ssh_pass
      prompt: "Enter SSH password for initial access"
      private: yes

  tasks:
    - name: Deploy SSH public key to user
      authorized_key:
        user: "{{ ssh_user }}"
        state: present
        key: "{{ lookup('file', local_pubkey_path) }}"

