---
- name: Ensure known_hosts is updated
  hosts: all
  gather_facts: no

  tasks:
    - name: Scan and add host key to control node's known_hosts
      known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -T 5 ' ~ inventory_hostname) }}"
        path: "~/.ssh/known_hosts"
        state: present
      delegate_to: localhost
      run_once: false
