---
- name: Configure hostname and /etc/hosts for centos_clients
  hosts: centos_clients
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Parse FQDN to get short hostname
      ansible.builtin.set_fact:
        short_hostname: "{{ hostname.split('.')[0] }}"

    - name: Set the system hostname using short hostname only
      ansible.builtin.command:
        cmd: hostnamectl set-hostname "{{ short_hostname }}"
      register: hostnamectl_result

    - name: Confirm hostname was set
      debug:
        msg: "Hostname set to {{ short_hostname }} on {{ inventory_hostname }}"
