---
- name: Add remote host SSH keys to known_hosts on the controller
  hosts: all
  gather_facts: no

  tasks:
    - name: Scan and add SSH host key to controller's known_hosts
      known_hosts:
        name: "{{ inventory_hostname }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -T 5 ' + inventory_hostname) }}"
        path: "~/.ssh/known_hosts"
        state: present
      delegate_to: localhost
